# Site settings
title: In't kort
header-img: img/home-bg.jpg
email: intkortuitgelegd@gmail.com
description: "Technische vragen kort uitgelegd door Sebastiaan Jansen"
baseurl: ""
url: "https://intkort.be"
twitter_username: 
github_username: intkort/intkort.github.io
facebook_username:  
google_analytics: UA-68037711-1

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
kramdown:
    auto_ids: false